services:
  nexterm:
    build:
      context: .
      dockerfile: Dockerfile 

    env_file:
      - .env
    environment:
      ENCRYPTION_KEY: "aba3aa8e29b9904d5d8d705230b664c053415c54be20ad13be99af0057dfa23a" # Replace key in .env    
    ports:
      - "6990:6989"
    restart: always
    volumes:
      - nexterm:/app/data
    #image: germannewsmaker/nexterm:1.0.2-OPEN-PREVIEW
    image: nexterm:dev
    container_name: nexterm-dev
volumes:   
  nexterm:
